trigger:
  branches:
    include:
      - master
  paths:
    include:
      - pern-todo-app/*
      - pipeline/App-Container-CI Pipeline.yaml

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: 'gbp-sc-ritesh'
  acrName: 'acr3tierfylxnlaj2ey4a'
  acrLoginServer: 'acr3tierfylxnlaj2ey4a.azurecr.io'
  backendImage: 'todo-backend'
  frontendImage: 'todo-frontend'
  tag: '$(Build.BuildId)'

stages:
- stage: BuildAndPush
  displayName: 'Build and Push Stage'
  jobs:
  - job: DockerBuild
    steps:
    - checkout: self

    - task: AzureCLI@2
      displayName: 'Build and Push via Azure CLI'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az acr login --name $(acrName)
          
          # 1. Build and Push Backend
          docker build -t $(acrLoginServer)/$(backendImage):$(tag) \
                       -t $(acrLoginServer)/$(backendImage):latest \
                       -f pern-todo-app/backend/Dockerfile pern-todo-app/backend
          
          docker push $(acrLoginServer)/$(backendImage):$(tag)
          docker push $(acrLoginServer)/$(backendImage):latest
          
          docker build -t $(acrLoginServer)/$(frontendImage):$(tag) \
                       -t $(acrLoginServer)/$(frontendImage):latest \
                       -f pern-todo-app/frontend/Dockerfile pern-todo-app/frontend
          
          docker push $(acrLoginServer)/$(frontendImage):$(tag)
          docker push $(acrLoginServer)/$(frontendImage):latest