trigger: none # Manually triggered or follows CI

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: 'gbp-sc-ritesh'
  resourceGroupName: 'gbp-devops-ritesh'
  acrName: 'acr3tierfylxnlaj2ey4a'
  imageTag: 'latest' 

stages:
- stage: DeployToProduction
  displayName: 'Deploy to Azure Container Apps'
  jobs:
  - job: Deploy
    steps:
    # 1. Deploy Backend Container
    - task: AzureContainerApps@1
      displayName: 'Deploy Backend App'
      inputs:
        azureSubscription: $(azureServiceConnection)
        resourceGroup: $(resourceGroupName)
        containerAppName: 'aca-api'
        imageToDeploy: '$(acrName).azurecr.io/todo-backend:$(imageTag)'

    # 2. Deploy Frontend Container 
    # (Removed envVars because Bicep handles VITE_API_URL automatically)
    - task: AzureContainerApps@1
      displayName: 'Deploy Frontend App'
      inputs:
        azureSubscription: $(azureServiceConnection)
        resourceGroup: $(resourceGroupName)
        containerAppName: 'aca-frontend'
        imageToDeploy: '$(acrName).azurecr.io/todo-frontend:$(imageTag)'