trigger: none 

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: 'gbp-sc-ritesh'
  resourceGroupName: 'gbp-devops-ritesh'
  acrName: 'acr3tierfylxnlaj2ey4a'
  imageTag: 'latest' 

stages:
- stage: DeployToProduction
  displayName: 'Deploy to Azure Container Apps'
  jobs:
  - job: Deploy
    steps:
    - task: AzureCLI@2
      displayName: 'Update Container App Images'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # 1. Update Backend Image
          az containerapp update \
            --name aca-api \
            --resource-group $(resourceGroupName) \
            --image $(acrName).azurecr.io/todo-backend:$(imageTag)

          # 2. Update Frontend Image
          az containerapp update \
            --name aca-frontend \
            --resource-group $(resourceGroupName) \
            --image $(acrName).azurecr.io/todo-frontend:$(imageTag)